#!/bin/sh
neutron router-gateway-clear PublicRouter
neutron router-interface-delete PublicRouter PublicLAN
neutron router-interface-delete  PublicRouter $subnets
neutron router-delete PublicRouter
neutron net-delete PublicLAN
